In [1]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [2]:
!wget https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt
!wget https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt

--2024-09-04 16:16:07--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26622 (26K) [text/plain]
Saving to: ‘edgar_allan_poe.txt’

edgar_allan_poe.txt 100%[===================>]  26.00K  --.-KB/s    in 0.001s  

2024-09-04 16:16:07 (48.0 MB/s) - ‘edgar_allan_poe.txt’ saved [26622/26622]

--2024-09-04 16:16:07--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP re

In [3]:
input_files = [
    "edgar_allan_poe.txt",
    "robert_frost.txt"
]

In [4]:
!head edgar_allan_poe.txt

LO! Death hath rear'd himself a throne
In a strange city, all alone,
Far down within the dim west
Where the good, and the bad, and the worst, and the best,
Have gone to their eternal rest.
 
There shrines, and palaces, and towers
Are not like any thing of ours
Oh no! O no! ours never loom
To heaven with that ungodly gloom!


In [5]:
!head robert_frost.txt

Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth; 

Then took the other, as just as fair,
And having perhaps the better claim
Because it was grassy and wanted wear,
Though as for that the passing there


In [6]:
# collect data into lists
input_texts = []
labels = []

for label, f in enumerate(input_files):
    print(f"{f} corresponds to label {label}")

    for line in open(f):
        line = line.rstrip().lower()
        if line:
            # remove punctuations
            line = line.translate(str.maketrans('', '', string.punctuation))

            input_texts.append(line)
            labels.append(label)

edgar_allan_poe.txt corresponds to label 0
robert_frost.txt corresponds to label 1


In [7]:
train_text, test_text, Ytrain, Ytest = train_test_split(input_texts, labels)

In [8]:
len(Ytrain), len(Ytest)

(1615, 539)

In [9]:
train_text[:5]

['and what do you see',
 'the sun in the newcut narrow gap',
 'and then becoming reconciled',
 'then my heart it grew ashen and sober',
 'in the fever of a minute']

In [10]:
Ytrain[:5]

[1, 1, 1, 0, 0]

In [11]:
idx = 1
word2idx = {'<unk>': 0}

In [12]:
# populate word2idx
for text in train_text:
    tokens = text.split()
    for token in tokens:
        if token not in word2idx:
            word2idx[token] = idx
            idx += 1

In [13]:
word2idx

{'<unk>': 0,
 'and': 1,
 'what': 2,
 'do': 3,
 'you': 4,
 'see': 5,
 'the': 6,
 'sun': 7,
 'in': 8,
 'newcut': 9,
 'narrow': 10,
 'gap': 11,
 'then': 12,
 'becoming': 13,
 'reconciled': 14,
 'my': 15,
 'heart': 16,
 'it': 17,
 'grew': 18,
 'ashen': 19,
 'sober': 20,
 'fever': 21,
 'of': 22,
 'a': 23,
 'minute': 24,
 'with': 25,
 'fervor': 26,
 'thy': 27,
 'lute': 28,
 'where': 29,
 'chimney': 30,
 'started': 31,
 'above': 32,
 'stove': 33,
 'not': 34,
 'that': 35,
 'he': 36,
 'hadnt': 37,
 'gnawed': 38,
 'hitching': 39,
 'posts': 40,
 'from': 41,
 'their': 42,
 'melancholy': 43,
 'throats': 44,
 'seems': 45,
 'as': 46,
 'if': 47,
 'thats': 48,
 'all': 49,
 'hes': 50,
 'helpless': 51,
 'can': 52,
 'reckon': 53,
 'our': 54,
 'cousinship': 55,
 'saturn': 56,
 'mars': 57,
 'after': 58,
 'manner': 59,
 'stock': 60,
 'but': 61,
 'meddle': 62,
 'fate': 63,
 'for': 64,
 'gods': 65,
 'sake': 66,
 'arent': 67,
 'fond': 68,
 'viewing': 69,
 'nature': 70,
 'yet': 71,
 'knowing': 72,
 'how': 73,
 '

In [14]:
len(word2idx)

2542

In [15]:
# convert data ubto integer format
train_text_int = []
test_text_int = []

for text in train_text:
    tokens = text.split()
    line_as_int = [word2idx[token] for token in tokens]
    train_text_int.append(line_as_int)

for text in test_text:
    tokens  = text.split()
    line_as_int = [word2idx.get(token, 0) for token in tokens]
    test_text_int.append(line_as_int)

In [16]:
train_text_int[100:105]

[[374, 375, 157, 23, 376, 103, 87, 377, 378],
 [1, 379, 23, 380, 381, 6, 382, 383],
 [76, 163, 384, 340, 50, 385, 61, 46, 77, 386],
 [387, 379, 388, 389, 15, 390],
 [46, 47, 6, 391, 134, 392, 393]]

In [17]:
test_text_int[100:105]

[[48, 265, 74, 64, 23, 609, 77, 3, 120, 163, 423],
 [4, 315, 274, 1890, 408, 601, 91, 173, 2],
 [8, 0, 41, 172, 76, 1, 437, 0, 96],
 [107, 2256, 0, 22, 1317],
 [215, 315, 229, 189, 46, 0, 1359, 0, 158, 1987]]

In [18]:
# initialize A and pi matrixes for both classes
V = len(word2idx)

A0 = np.ones((V, V))
pi0 = np.ones(V)

A1 = np.ones((V, V))
pi1 = np.ones(V)


In [20]:
# compute counst for A and pi
def compute_counts(text_as_int, A, pi):
    for token in text_as_int:
        last_idx = None
        for idx in token:
            if last_idx is None:
                # it's the first word in a sentence
                pi[idx] += 1
            else:
                # the last work exists, so count a transition
                A[last_idx, idx] += 1
            # update last idx
            last_idx = idx

compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [21]:
# normalize A and pi so they are valid probability matrices
# convince yourself that this is equivalent to the formulars shown before
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [22]:
pi0

array([0.00032478, 0.0168886 , 0.00064956, ..., 0.00032478, 0.00032478,
       0.00032478])

In [23]:
# log A and pi since we don't need the actual probs
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [24]:
# compute priors
count0 = sum(y == 0 for y in Ytrain)
count1 = sum(y == 1 for y in Ytrain)
total = len(Ytrain)
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0, p1

(0.33250773993808047, 0.6674922600619195)

In [25]:
# build a classifier
class Classifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors) # number of classes

    def _compute_log_likelihood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]

        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                # it's the first token
                logprob += logpi[idx]
            else:
                logprob += logA[last_idx, idx]
            # update last_idx
            last_idx = idx
        return logprob

    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            posterios = [self._compute_log_likelihood(input_, c) + self.logpriors[c] for c in range(self.K)]
            pred = np.argmax(posterios)
            predictions[i] = pred
        return predictions

In [26]:
# each array must be in order since classes are assumed to index these lists
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [27]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.9956656346749226


In [28]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.8256029684601113


In [29]:
from sklearn.metrics import confusion_matrix, f1_score

In [30]:
cm = confusion_matrix(Ytrain, Ptrain)
cm

array([[ 530,    7],
       [   0, 1078]])

In [31]:
cm_test = confusion_matrix(Ytest, Ptest)
cm_test

array([[ 97,  84],
       [ 10, 348]])

In [32]:
f1_score(Ytrain, Ptrain)

0.9967637540453074

In [33]:
f1_score(Ytest, Ptest)

0.8810126582278481