In [26]:
import zipfile
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [27]:
with zipfile.ZipFile("/content/airfoil+self+noise.zip") as thezip:
    thezip.extractall()

In [28]:
df = pd.read_csv("/content/airfoil_self_noise.dat", sep="\t", header=None)
df.head()

0    1       2     3         4        5
0   800  0.0  0.3048  71.3  0.002663  126.201
1  1000  0.0  0.3048  71.3  0.002663  125.201
2  1250  0.0  0.3048  71.3  0.002663  125.951
3  1600  0.0  0.3048  71.3  0.002663  127.591
4  2000  0.0  0.3048  71.3  0.002663  127.461

In [29]:
df.shape

(1503, 6)

In [30]:
data = df[[1,2,3,4]].values
data

array([[0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       [0.00000e+00, 3.04800e-01, 7.13000e+01, 2.66337e-03],
       ...,
       [1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02],
       [1.56000e+01, 1.01600e-01, 3.96000e+01, 5.28487e-02]])

In [31]:
targets = df[5].values

In [32]:
targets

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

In [33]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data, targets, test_size=0.33)

In [34]:
Xtrain.shape, Xtest.shape

((1007, 4), (496, 4))

In [35]:
model = LinearRegression()
model.fit(Xtrain, Ytrain)

LinearRegression()

In [36]:
model.score(Xtrain, Ytrain)

0.22872466771217614

In [37]:
model.score(Xtest, Ytest)

0.18720273554716627

In [38]:
predictions = model.predict(Xtest)

In [39]:
predictions

array([128.46566321, 120.67400224, 129.29716396, 126.79228276,
       122.4191116 , 121.6280727 , 126.86445471, 122.4191116 ,
       124.80476221, 120.93767026, 127.12815147, 122.90034008,
       127.87399079, 122.4191116 , 125.87455871, 125.36776297,
       127.97206869, 123.41105876, 129.06947006, 127.12815147,
       123.47567111, 127.97206869, 121.27275979, 121.12434258,
       121.12434258, 121.12434258, 122.68624291, 115.2490107 ,
       125.36776297, 121.12490423, 123.67984432, 124.74165394,
       123.8068309 , 120.66760233, 122.94514412, 121.27275979,
       126.02119821, 123.58085   , 127.28592466, 123.32221165,
       118.76347511, 122.54878255, 127.4701397 , 122.68624291,
       122.90034008, 128.59328854, 124.80476221, 120.67400224,
       123.24567795, 128.84539254, 124.3125411 , 123.32221165,
       128.34325487, 121.12434258, 126.99848293, 128.59328854,
       125.37958974, 121.28523169, 125.92875537, 123.58085   ,
       120.67191593, 129.29716396, 122.41958599, 122.56

In [40]:
model2 = RandomForestRegressor()
model2.fit(Xtrain, Ytrain)

RandomForestRegressor()

In [41]:
model2.score(Xtrain, Ytrain)

0.3306577433807606

In [42]:
model2.score(Xtest, Ytest)

0.14654120065341758